# Generated by Django 3.1.6 on 2021-02-06 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.BigIntegerField(default=0),
        ),
    ]
